version: "3.8"
services:
  caddy:
    image: ghcr.io/henrikgrubbe/ravnely/caddy:latest
    ports:
      - "127.0.0.1:2080:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

# Websites
  breadboard-pc-programmer:
    image: ghcr.io/henrikgrubbe/breadboard-pc-programmer:latest
    depends_on:
      - node-mqtt
    restart: always

  chicken-tracker:
    image: ghcr.io/henrikgrubbe/chicken-tracker:latest
    restart: always

# Services
  node-mqtt:
    depends_on:
      - mqtt
    image: ghcr.io/henrikgrubbe/node-mqtt:latest
    environment:
      PORT: 80
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
    restart: always

  chicken-data-native:
    image: ghcr.io/henrikgrubbe/chicken-data-native:latest
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    restart: always

# Backing-services
  mqtt:
    image: eclipse-mosquitto:latest
    ports: 
      - "1883:1883"
    volumes:
      - ./volumes/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    restart: always

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  
