version: "3.8"
services:
  caddy:
    image: ghcr.io/henrikgrubbe/ravnely/caddy:latest
    ports:
      - "127.0.0.1:2080:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

# Websites
  breadboard-pc-programmer:
    image: ghcr.io/henrikgrubbe/breadboard-pc-programmer:latest
    depends_on:
      - node-mqtt
    restart: always

# Services
  node-mqtt:
    depends_on:
      - mqtt
    image: ghcr.io/henrikgrubbe/node-mqtt:latest
    environment:
      PORT: 80
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
    restart: always

  trash-notifier:
    image: ghcr.io/henrikgrubbe/trash:latest
    environment:
      CALENDAR_URL: values=N%C3%A5rupvej%7C21%7C%7C%7C%7C8883%7CGjern%7C22050160%7C784231%7C0
      CALENDAR_BODY: https://www.seerupit.com/toemningskalender/silkeborg/showInfo.php
    restart: always

# Backing-services
  mqtt:
    image: eclipse-mosquitto:latest
    ports: 
      - "1883:1883"
    volumes:
      - ./volumes/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

volumes:
  caddy_data:
  caddy_config:
